### PR TITLE
PyQt versions of SelectROI and FileRenamer added/ updated

### PR DESCRIPTION
**Pull request by JRMeyer**
SelectROI is fuctional, FileRenamer is still in development

### CODE REVIEW

**Comment by myedibleenso** [comment]
@JRMeyer it looks like you've included some temp files (ex. `FileRename_Qt.py~`).  Please remove these and push.  You might want to add a `.*~` pattern to `.gitignore` to avoid adding them accidentally in the future.

**Comment by myedibleenso** [comment]
When I run `SelectROI_Qt.py` and select a single `.jpg` file, it crashes with this error:

``` python
ValueError                                Traceback (most recent call last)
<ipython-input-3-0be69a7ff5cf> in <module>()
     37
     38 if __name__ == '__main__':
---> 39     main()

<ipython-input-3-0be69a7ff5cf> in main()
     31 def main():
     32     app = QtGui.QApplication(sys.argv)
---> 33     roi = ROI_selector()
     34     roi.destroy()
     35     sys.exit()

<ipython-input-3-0be69a7ff5cf> in __init__(self)
     10         super(ROI_selector, self).__init__()
     11         self.selectImages()
---> 12         self.getSumImage()
     13
     14     def selectImages(self):

<ipython-input-3-0be69a7ff5cf> in getSumImage(self)
     25                         img = cv2.imread(str(i))
     26                         tmp = numpy.zeros(self.csize)
---> 27                         tmp += img
     28                         sum_img += tmp
     29                 sum_img = sum_img/len(self.datafiles)

ValueError: operands could not be broadcast together with shapes (480,720) (480,720,3) (480,720)
```

**Comment by JRMeyer** [comment]
The input for SelectROI_Qt.py is a folder of images (a dir not a file).

If we want to change that I can. Let me know.

Also, a dependency for the script is pyqtgraph. http://www.pyqtgraph.org/
Pyqtgraph itself only depends on PyQt4 and numpy, and it handles ROI
selection very cleanly, which was my thinking in using it.

I mentioned the additional dependency at our last couple meetings and no
one seemed opposed. In general don't like adding on more, but it is a very
useful library.

2015-03-10 17:05 GMT-07:00 Gustave Hahn-Powell notifications@github.com:

> When I run SelectROI_Qt.py and select a single .jpg file, it crashes with
> this error:
> 
> ValueError                                Traceback (most recent call last)<ipython-input-3-0be69a7ff5cf> in <module>()
>      37
>      38 if **name** == '**main**':---> 39     main()
> <ipython-input-3-0be69a7ff5cf> in main()
>      31 def main():
>      32     app = QtGui.QApplication(sys.argv)---> 33     roi = ROI_selector()
>      34     roi.destroy()
>      35     sys.exit()
> <ipython-input-3-0be69a7ff5cf> in **init**(self)
>      10         super(ROI_selector, self).**init**()
>      11         self.selectImages()---> 12         self.getSumImage()
>      13
>      14     def selectImages(self):
> <ipython-input-3-0be69a7ff5cf> in getSumImage(self)
>      25                         img = cv2.imread(str(i))
>      26                         tmp = numpy.zeros(self.csize)---> 27                         tmp += img
>      28                         sum_img += tmp
>      29                 sum_img = sum_img/len(self.datafiles)
> ValueError: operands could not be broadcast together with shapes (480,720) (480,720,3) (480,720)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jjberry/Autotrace/pull/8#issuecomment-78175572.

## 

Joshua Meyer
Ph.D. Student
Linguistics Department
University of Arizona

**Comment by myedibleenso** [comment]
Hmm... it will only allow me to select images (the message at the top of the window also seems to suggest that's what the user should do).  Still no luck.  Any ideas?

screen shot 2015-03-10 at 5 55 29 pm

**Comment by myedibleenso** [comment]
@JRMeyer can you reopen this request on the [APIL fork of AutoTrace](https://github.com/arizona-phonological-imaging-lab/Autotrace)?  Before doing that, though, I think some of this stuff should be moved to the [data-analysis](https://github.com/arizona-phonological-imaging-lab/data-analysis) repo.

**Pull request closed without merging**
